SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."experiance_types" AS ENUM (
    'IMAX',
    'GOLD',
    'ATMOS',
    'Digital'
);

ALTER TYPE "public"."experiance_types" OWNER TO "postgres";


CREATE TYPE "public"."locations" AS ENUM (
    'HCM',
    'CCC',
    'LIBERTY'
);


ALTER TYPE "public"."locations" OWNER TO "postgres";

CREATE TYPE "public"."user_type" AS ENUM (
    'ADMIN',
    'USER'
);

ALTER TYPE "public"."user_type" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."registered_alerts_by_id" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "active" boolean,
    "user" "text",
    "movie_id" "text",
    "date" timestamp without time zone[] NOT NULL,
    "location" "public"."locations" NOT NULL,
    "experiance" "public"."experiance_types"[] NOT NULL
);


ALTER TABLE "public"."registered_alerts_by_id" OWNER TO "postgres";


ALTER TABLE "public"."registered_alerts_by_id" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."registered_alerts_by_id_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."registered_alerts_by_id"
    ADD CONSTRAINT "registered_alerts_by_id_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."registered_alerts_by_id" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";